name: Build Backend
on:
  push:
    branches: [ "main" ]
jobs:
  build_backend:
    name: Build backend
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY_URL }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REGISTRY_URL }}/kubernetes-enabled/diffusion-lab-ci/backend:${{ github.sha }}
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/kubernetes-enabled/diffusion-lab-ci/backend:${{ github.sha }}
  trigger:
    name: Trigger deploy
    needs: build_backend
    runs-on: ubuntu-24.04
    steps:
    - name: Trigger GitLab pipeline
      run: |
        curl -X POST \
        --fail \
        -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
        -F ref=main \
        -F "variables[COMMIT_SHA]=${{ github.sha }}" \
        ${{ secrets.GITLAB_TRIGGER_URL }}
