name: Build Backend
on:
  push:
    branches: [ "main" ]
jobs:
  build_backend:
    name: Build Backend
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY_URL }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build \
        --file Dockerfile \
        --build-arg SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}" \
        --build-arg SSH_PUBLIC_KEY="${{ secrets.SSH_PUBLIC_KEY }}" \
        --tag ${{ secrets.DOCKER_REGISTRY_URL }}/kubernetes-enabled/diffusion-lab-ci/backend:${{ github.sha }} \    
        . 
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/kubernetes-enabled/diffusion-lab-ci/backend:${{ github.sha }}
  
  build_frontend:
    name: Build Frontend
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY_URL }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build \
        --file Dockerfile \
        --build-arg VITE_BACKEND_URL="${{ secrets.BACKEND_URL }}"
        --tag ${{ secrets.DOCKER_REGISTRY_URL }}/kubernetes-enabled/diffusion-lab-ci/frontend:${{ github.sha }} \
        .
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_REGISTRY_URL }}/kubernetes-enabled/diffusion-lab-ci/frontend:${{ github.sha }}
  
  trigger:
    name: Trigger deploy
    needs:
      - build_backend
      - build_frontend
    runs-on: ubuntu-24.04
    steps:
    - name: Trigger GitLab pipeline
      run: |
        curl -X POST \
        --fail \
        -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} \
        -F ref=main \
        -F "variables[COMMIT_SHA]=${{ github.sha }}" \
        ${{ secrets.GITLAB_TRIGGER_URL }}
